### ISSUE TITLE
[BUG] - '@get:' annotations are moved to function which in dto input Builder, and cant be compiled

### ISSUE THREAD

**Issue by yangpanda** [babyfish-ct/jimmer#1010]
### Jimmer Version

0.9.78   

### ksp version
2.1.20-2.0.0

### JDK Version

21

### Database

pg

### OS

Windows

### Expected behavior

dont add get:

### Actual behavior

@get:JsonFormat: be moved

### Description

![Image](https://github.com/user-attachments/assets/7a49c8e4-4e00-4825-881c-90e36a0d1b13)

![Image](https://github.com/user-attachments/assets/d82038e7-5434-46bf-b3c9-3e63d208541e)

### Reproduction steps

none

**Comment by yangpanda** [comment]
no bug.   but i dont know why, may be gradle cache cause this issue

**Comment by yangpanda** [comment]
[jimmer-demo.zip](https://github.com/user-attachments/files/19927008/jimmer-demo.zip)

**Comment by babyfish-ct** [comment]
Duplicated to #1005, has been fixed

Upgrade to 0.9.78, and upgrade kotlin and KSP
- Kotlin: 2.1.20
- KSP: 2.1.20-2.0.0

**Comment by yangpanda** [comment]
yes, it is 0.9.78, maybe not fixed,  you can try the demo i upload

**Comment by babyfish-ct** [comment]
ok

**Comment by babyfish-ct** [comment]
Try `0.9.79`

**Comment by yangpanda** [comment]
Thank you. But there are still some problems,  in the generated code missing two import.
![Image](https://github.com/user-attachments/assets/6ff9928b-bcd1-4ab0-ba26-918d90cda270)

**Comment by babyfish-ct** [comment]
That is bug of kotllinpeot, I will upgrade the kotlin/KSP of framework again.

**Comment by yangpanda** [comment]
got it, thank you

**Comment by babyfish-ct** [comment]
https://repo1.maven.org/maven2/org/babyfish/jimmer/jimmer-sql-kotlin/0.9.80

It looks like maven central is broken, this file cannot be refreshed after long waiting.

**Comment by babyfish-ct** [comment]
But actually it works, just try `0.9.80`
